apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: promgateway-demo
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: promgateway-demo
            image: promgateway-demo:1
            args:
            - "--pushgateway"
            - "http://promgateway-demo-prometheus-pushgateway:9091"
            - "@/config/urls"
            volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: promgateway-demo
                items:
                  - key: urls
                    path: urls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promgateway-demo
data:
  urls: |
    https://oro.nu
    https://blog.oro.nu
    https://orovecchia.at
    https://oro.nu/does_not_exist
    https://expired.badssl.com/
    https://revoked.badssl.com/
    https://https-everywhere.badssl.com/
    http://httpstat.us/200
    http://httpstat.us/300
    http://httpstat.us/400
    http://httpstat.us/404
    http://httpstat.us/204
    http://example.invalid
