apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: promgateway-demo
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: promgateway-demo
            image: promgateway-demo
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecosio-interview
data:
  urls:
    - https://blog.oro.nu
